# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

stages:
  - stage: HelmPackage
    displayName: Helm Package and Install to AKS cluster
    jobs:
      - job: CreatePackage
        displayName: Create Helm Package
        steps:
          - task: HelmDeploy@0
            inputs:
              command: 'package'
              chartPath: '.'
              chartVersion: $(Build.BuildId)
          - task: PublishPipelineArtifact@1
            inputs:
              targetPath: '$(Build.ArtifactStagingDirectory)'
              artifact: 'exporter-chart'
              publishLocation: 'pipeline'
          - task: HelmDeploy@0
            inputs:
              connectionType: 'Azure Resource Manager'
              azureSubscription: 'Free Trial(9aa7f2ca-18ba-4733-abc7-a3824511edf0)'
              azureResourceGroup: 'azuretestrg'
              kubernetesCluster: 'myaks'
              command: 'install'
              chartPath: '.'
              chartVersion: $(Build.BuildId)
          