replicaCount: 1

image:
  repository: webdevops/azure-devops-exporter
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: "latest"

service:
  type: ClusterIP
  port: 8080

azureDevops:
  token: Z2l5dXZ1bjVuN28zZWNkdndybXg2eWNoeXRmYWFtaWN0Znk0c2pocG53N3RndmNkdXJxYQ==
  url: https://dev.azure.com
  org: isapur-hat