replicaCount: 1

image:
  repository: webdevops/azure-devops-exporter
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: "latest"
  containerPort: 8080

service:
  type: ClusterIP
  port: 8080

azureDevops:
  token: anJldHFseTVvcnc1cGpkcmx4YmZjN2p5bnRubzU3aDVnc2FrczZvZHRza3h2emxlYWpvYQ==
  url: https://dev.azure.com
  org: isapur-hat