apiVersion: apps/v1
kind: Deployment
metadata:
  name: azure-devops-exporter-deployment
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: azure-devops-exporter-pod
  template:
    metadata:
      labels:
        app: azure-devops-exporter-pod
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
           - name: AZURE_DEVOPS_URL
             value:  "{{ .Values.azureDevops.url }}"
           - name: AZURE_DEVOPS_ORGANISATION
             value: "{{ .Values.azureDevops.org }}"
           - name: AZURE_DEVOPS_ACCESS_TOKEN
             valueFrom: 
               secretKeyRef: 
                 key: azure-devops-token
                 name: azure-devops-secret-token
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP