apiVersion: apps/v1
kind: Deployment
metadata:
  name: azure-devops-exporter-deployment
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: azure-devops-exporter-pod
  template:
    metadata:
      labels:
        app: azure-devops-exporter-pod
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
           - name: AZURE_DEVOPS_URL
             value: "https://dev.azure.com"
           - name: AZURE_DEVOPS_ORGANISATION
             value: "isapur-hat"
           - name: AZURE_DEVOPS_ACCESS_TOKEN
             value: "giyuvun5n7o3ecdvwrmx6ychytfaamictfy4sjhpnw7tgvcdurqa"
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP