apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-deployment
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}-pod
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-pod  #pod label must be same as selector match labels
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
           - name: AZURE_DEVOPS_URL
             value:  "{{ .Values.azureDevops.url }}"
           - name: AZURE_DEVOPS_ORGANISATION
             value: "{{ .Values.azureDevops.org }}"
           - name: AZURE_DEVOPS_ACCESS_TOKEN
             valueFrom: 
               secretKeyRef: 
                 key: azure-devops-token
                 name: {{ .Release.Name }}-secret-token
          ports:
            - name: http
              containerPort: {{ .Values.image.containerPort }}
              protocol: TCP