apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-service
spec:
  # by defalut service type is ClusterIP 
  # (Internal networking, can't be accessed by external service or client) 
  # NodePort service can be access by external services
  type: {{ .Values.service.type }}  
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app: {{ .Release.Name }}-pod